name: 'Update the scs-repository'
description: 'Update the scs-repository with the new helm chart version'
inputs:
  short-sha:
    description: 'The short SHA value of the git commit'
    required: true
  scs-name:
    description: 'The name of the scs'
    required: true
  service-name:
    description: 'The name of the service to update'
    required: true
runs:
  using: "composite"
  steps:
    - name: Set up git config and update tag version in values
      shell: bash
      working-directory: scs
      run: |
        git config user.name "$GITHUB_ACTOR"
        git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

        wget https://github.com/mikefarah/yq/releases/download/v4.14.1/yq_linux_amd64 && chmod +x yq_linux_amd64

        export IMAGE_TAG="sha-${{ inputs.short-sha }}"
        ./yq_linux_amd64 eval '.${{ inputs.service-name }}.image.tag = strenv(IMAGE_TAG)' -i ${{ inputs.scs-name }}/values.yaml

        git add "${{ inputs.scs-name }}/values.yaml"
        git commit -m "Upgraded version of ${{ inputs.scs-name }} to 1.0.0-sha${{ inputs.short-sha }}"
        git push
